### ISSUE TITLE
Nuget package approval

### ISSUE THREAD

**Issue by evest** [zanganeh/RobotsTxtHandler#1]
Thanks for contributing the package to the Episerver Nuget Feed.

Before approving it, could you please add some documentation about what it does?

As far as I can see, it only responds with `Useragent: * ` for the robots.txt request, so what is the benefit over a physical file?

**Comment by zanganeh** [comment]
Hi

Thanks for reviewing this package. my aim is for multi site application to
have an area to define robot text for each site separately and one for
global which individual site can inherit from it. I released first  version
and I'm working on second version. admin UI is a bit pain in this stage.
then next version is to add we.cnfig settING so on UAT environment dev can
override all robot text to avoid stage site being detected by crawlers. if
I can get first version in I will accelerate other versions.

Regards
Aria

**Comment by evest** [comment]
Sounds like good features to add, and a package that people would want to use. I propose we wait until you have a base feature set in place before we add the package to the feed.

If you are in need of hosting the package in a feed to satisfy a build server or sharing with coworkers, I highly recommend [MyGet](http://www.myget.org). Personally I use it to test and share pre-release packages before I commit them to the Episerver Nuget Feed.

**Comment by zanganeh** [comment]
Great .. yeah we r on paid plan with them but for opesource I think it is
free. I will try and try finish mvp asap and get back to you. Again thank
for your help and advise.

**Comment by zanganeh** [comment]
@evest  new version is up. This version we support  multi-site and admin area which admin can  enter robots.txt per site! Do you want me to upload to episerver nuger first?

**Comment by evest** [comment]
I approved the package after you re-submitted it. Nice work!
